# YOLOv8n + ByteTrack Configuration
perception: 
  detection:
    model: yolo8n
    class_names: ['plane', 'ship', 'large-vehicle', 'small-vehicle', 'helicopter']
    confidence_threshold: 0.8
    iou_threshold: 0.4
    device: cuda

  tracking:
    enabled: true
    algorithm: bytetrack

  input:
    slice:
      active: true
      size:
        height: 640
        width: 640
      overlap:
        height_ratio: 0.2
        width_ratio: 0.2
      verbose: false

  



